"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Send, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { ShiningText } from "@/components/copied-ui/effects/ShiningText";
import { getClientAuthHeaders } from "@/lib/client-auth";
interface Msg{role:"user"|"ai";text:string}
const starters=["Plan 7 posts for my restaurant","Rewrite this caption for Instagram","Generate a launch campaign","Suggest the best posting time"];
export default function AI(){const[input,setInput]=useState("");const[messages,setMessages]=useState<Msg[]>([{role:"ai",text:"What should we create today?"}]);const[busy,setBusy]=useState(false);const send=async(text:string)=>{if(!text.trim()||busy)return;setMessages(current=>[...current,{role:"user",text}]);setInput("");setBusy(true);try{const response=await fetch("/api/ai/assistant",{method:"POST",headers:await getClientAuthHeaders({"Content-Type":"application/json"}),body:JSON.stringify({prompt:text})});const body=await response.json().catch(()=>null) as {suggestions?:string[];message?:string}|null;if(!response.ok)throw new Error(body?.message??"AI request failed");setMessages(current=>[...current,{role:"ai",text:body?.suggestions?.join("\n\n")??"No suggestions returned."}]);}catch(error){toast.error(error instanceof Error?error.message:"AI request failed");}finally{setBusy(false);}};return <div className="space-y-5 max-w-4xl mx-auto"><div><h1 className="font-display text-3xl font-bold tracking-tight flex items-center gap-2"><Sparkles className="h-6 w-6 text-accent"/><ShiningText>AI Assistant</ShiningText></h1><p className="text-sm text-muted-foreground">Your on-brand writer, planner and hashtag generator.</p></div><div className="flex flex-wrap gap-2">{starters.map(prompt=><button key={prompt} onClick={()=>void send(prompt)} className="rounded-full border border-border bg-secondary/40 px-3 py-1.5 text-xs hover:bg-secondary hover:border-primary/30 transition">{prompt}</button>)}</div><div className="glass rounded-2xl p-5 space-y-5 min-h-[400px]"><AnimatePresence initial={false}>{messages.map((message,index)=><motion.div key={index} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className={`flex gap-3 ${message.role==="user"?"justify-end":""}`}>{message.role==="ai"?<div className="h-8 w-8 shrink-0 grid place-items-center rounded-lg bg-gradient-primary text-primary-foreground"><Sparkles className="h-4 w-4"/></div>:null}<div className={`max-w-[80%] rounded-2xl p-3.5 text-sm whitespace-pre-wrap ${message.role==="user"?"bg-gradient-primary text-primary-foreground":"bg-secondary/60"}`}>{message.text}</div></motion.div>)}</AnimatePresence>{busy?<div className="text-xs text-muted-foreground">Creator AI is thinking...</div>:null}</div><form onSubmit={event=>{event.preventDefault();void send(input);}} className="glass rounded-2xl p-2 flex items-center gap-2"><input value={input} onChange={event=>setInput(event.target.value)} placeholder="Ask anything..." className="flex-1 bg-transparent px-3 text-sm focus:outline-none placeholder:text-muted-foreground"/><Button type="submit" disabled={busy} className="bg-gradient-primary text-primary-foreground"><Send className="h-4 w-4"/></Button></form></div>;}
