"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { addDays, addMonths, format, isSameDay, startOfMonth, startOfWeek } from "date-fns";
import { ChevronLeft, ChevronRight, Filter, Plus } from "lucide-react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { PlatformBadge, PlatformStack } from "@/components/copied-ui/PlatformBadge";
import { SkeletonLine } from "@/components/copied-ui/Skeletons";
import { listPostsByStatus } from "@/lib/posts";
import { toUiPost, type UiPost } from "@/lib/ui-repo-adapters";

const views = ["Month","Week","List"] as const;
export default function Calendar() {
  const [loading,setLoading]=useState(true); const [posts,setPosts]=useState<UiPost[]>([]); const [cursor,setCursor]=useState(new Date()); const [view,setView]=useState<typeof views[number]>("Month"); const [selectedDay,setSelectedDay]=useState(new Date());
  useEffect(()=>{ void listPostsByStatus(["Scheduled"]).then(items=>setPosts(items.map(toUiPost))).finally(()=>setLoading(false)); },[]);
  const days=Array.from({length:42},(_,index)=>addDays(startOfWeek(startOfMonth(cursor)),index)); const postsForDay=(day:Date)=>posts.filter(post=>isSameDay(new Date(post.scheduledAt),day)); const selectedPosts=postsForDay(selectedDay);
  if(loading)return <div className="space-y-5"><div className="space-y-2"><SkeletonLine className="h-8 w-48"/><SkeletonLine className="h-3 w-72"/></div><div className="glass rounded-2xl p-4 space-y-3"><div className="flex justify-between"><SkeletonLine className="h-6 w-40"/><SkeletonLine className="h-6 w-32"/></div><div className="grid grid-cols-7 gap-1">{Array.from({length:42}).map((_,index)=><SkeletonLine key={index} className="h-[90px] rounded-xl"/>)}</div></div></div>;
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-display text-3xl font-bold tracking-tight">Calendar</h1><p className="text-sm text-muted-foreground">Plan the week. Click a day for details.</p></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" className="border-border"><Filter className="mr-1.5 h-3.5 w-3.5"/> Filters</Button><Button asChild className="bg-gradient-primary text-primary-foreground shadow-glow"><Link href="/create"><Plus className="mr-1 h-4 w-4"/> New post</Link></Button></div></div>
    <div className="glass rounded-2xl p-4"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><button onClick={()=>setCursor(addMonths(cursor,-1))} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-secondary"><ChevronLeft className="h-4 w-4"/></button><div className="font-display text-xl font-semibold">{format(cursor,"MMMM yyyy")}</div><button onClick={()=>setCursor(addMonths(cursor,1))} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-secondary"><ChevronRight className="h-4 w-4"/></button></div><div className="flex gap-0.5 rounded-lg bg-secondary p-0.5 text-xs">{views.map(name=><button key={name} onClick={()=>setView(name)} className={`px-3 py-1.5 rounded-md transition ${view===name?"bg-background text-foreground shadow":"text-muted-foreground"}`}>{name}</button>)}</div></div>
      <div className="grid grid-cols-7 gap-1 text-[10px] uppercase tracking-wider text-muted-foreground mb-1">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><div key={day} className="px-2 py-1">{day}</div>)}</div><div className="grid grid-cols-7 gap-1">{days.map((day,index)=>{const items=postsForDay(day), inMonth=day.getMonth()===cursor.getMonth(),selected=isSameDay(day,selectedDay),today=isSameDay(day,new Date());return <motion.button key={index} whileHover={{scale:1.01}} onClick={()=>setSelectedDay(day)} className={`relative min-h-[90px] rounded-xl border p-2 text-left transition ${selected?"border-primary/50 bg-primary/10":"border-border bg-secondary/20 hover:bg-secondary/40"} ${!inMonth?"opacity-40":""}`}><div className={`text-xs font-semibold ${today?"inline-grid h-5 w-5 place-items-center rounded-full bg-gradient-primary text-primary-foreground":""}`}>{format(day,"d")}</div><div className="mt-1.5 space-y-1">{items.slice(0,3).map(post=><div key={post.id} className="flex items-center gap-1 truncate text-[10px]"><PlatformBadge platform={post.platforms[0] ?? "facebook"} size="xs"/><span className="truncate text-foreground/80">{post.caption.slice(0,18)}...</span></div>)}{items.length>3?<div className="text-[9px] text-muted-foreground">+{items.length-3} more</div>:null}</div></motion.button>;})}</div>
    </div>
    <div className="glass rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div><div className="text-xs uppercase tracking-wider text-muted-foreground">Selected day</div><div className="font-display text-xl font-semibold">{format(selectedDay,"EEEE, MMMM d")}</div></div><Button size="sm" asChild className="bg-gradient-primary text-primary-foreground"><Link href="/create"><Plus className="mr-1 h-3.5 w-3.5"/> Add post</Link></Button></div>{selectedPosts.length===0?<div className="rounded-xl border border-dashed border-border bg-secondary/20 p-10 text-center"><div className="font-semibold">Nothing scheduled</div><p className="mt-1 text-sm text-muted-foreground">Add content to fill this day.</p></div>:<div className="grid gap-3 md:grid-cols-2">{selectedPosts.map(post=><Link href={`/edit-post/${post.id}`} key={post.id} className="rounded-xl border border-border bg-secondary/30 p-4 hover-lift"><div className="flex items-center justify-between text-[11px] text-muted-foreground"><span>{format(new Date(post.scheduledAt),"HH:mm")}</span><PlatformStack platforms={post.platforms}/></div><p className="mt-2 text-sm">{post.caption}</p><div className="mt-3 text-[11px] text-muted-foreground">by {post.author.name}</div></Link>)}</div>}</div>
  </div>;
}
