import { format } from "date-fns";
import { ar as arDateLocale } from "date-fns/locale";

import type { Locale } from "@/lib/i18n";
import type { UiPlatform, UiPostStatus } from "@/lib/ui-repo-adapters";

export const pageCopy = {
  en: {
    common: {
      addPost: "Add post",
      allPosts: "All posts",
      askAi: "Ask AI",
      by: "by",
      channels: "Channels",
      clicks: "Clicks",
      connect: "Connect",
      connected: "Connected",
      connectChannel: "Connect a channel",
      delete: "Delete",
      disconnect: "Disconnect",
      edit: "Edit",
      engagement: "Engagement",
      failed: "Failed",
      granted: "Granted",
      hideFailed: "Hide failed",
      impressions: "Impressions",
      missing: "Missing",
      newPost: "New post",
      notConnected: "Not connected",
      opening: "Opening...",
      publishNow: "Publish now",
      reach: "Reach",
      reconnect: "Reconnect",
      save: "Save",
      showAll: "Show all",
      synced: "Synced",
      unknownDate: "Unknown date",
      untitledPost: "Untitled post",
      upload: "Upload",
      uploading: "Uploading...",
      viewAll: "View all",
    },
    dashboard: {
      title: "Creator command center",
      scheduledSummary: (posts: number, channels: number) =>
        `You have ${posts} posts scheduled across ${channels} channels.`,
      statScheduled: "Scheduled posts",
      statPublished: "Published",
      statDrafts: "Drafts",
      statChannels: "Connected channels",
      hintQueue: "publishing queue",
      hintPublished: "completed outcomes",
      hintDrafts: "stored ideas",
      hintChannels: "live destinations",
      gettingStarted: "Getting started",
      stepsComplete: (done: number, total: number) => `${done} of ${total} steps complete`,
      checklist: [
        "Connect your first channel",
        "Create your first post",
        "Schedule a week of content",
        "Review your first analytics report",
      ],
      aiInsight: "AI insight",
      queueHealthy: "Your publishing queue is healthy.",
      nextWindowOpen: "Your next publishing window is open.",
      aiBody: "Ask Creator AI to shape the next content move from your real workspace state.",
      todaysQueue: "Today's queue",
      noScheduled: "No scheduled posts yet.",
      topPost: "Top post",
      performance: "performance",
      publishedPlaceholder: "Published outcomes appear here.",
      channelHealth: "Channel health",
      manage: "Manage",
      publishingReady: "Publishing ready",
      needsAttention: "Needs attention",
    },
    create: {
      editTitle: "Edit post",
      title: "Compose post",
      subtitle: (autosave: string) => `Write once, preview everywhere. ${autosave}`,
      saved: "Saved",
      saving: "Saving...",
      saveDraft: "Save draft",
      schedule: "Schedule",
      ready: "Ready",
      selectedBadge: (count: number) => `${count} ch`,
      loadError: "Unable to load composer",
      mediaUploaded: "Media uploaded",
      uploadFailed: "Upload failed",
      requireContent: "Add a caption or media first",
      requireDestination: "Connect and select at least one publishing destination",
      requireTime: "Choose a schedule time",
      published: "Publishing complete",
      draftSaved: "Draft saved",
      scheduled: "Post scheduled",
      saveFailed: "Unable to save post",
      aiRewritePrompt: "Rewrite this caption to be clearer, engaging and platform-ready.",
      aiRewriteFailed: "AI rewrite failed",
      aiRewriteAdded: "AI rewrite added",
      linkPrompt: "Paste a URL to add to this post",
      suggestionPrompt: (suggestion: string) => `${suggestion}. Return one ready-to-use caption fragment only.`,
      suggestionFailed: "AI suggestion failed",
      suggestionAdded: "Suggestion added",
      noChannelToPublish: "Connect a channel to publish.",
      composerPlaceholder: "What's happening?",
      toolMedia: "Media",
      toolHashtags: "Hashtags",
      toolLink: "Link",
      toolEmoji: "Emoji",
      aiRewrite: "AI rewrite",
      media: "Media",
      aiSuggestions: "AI suggestions",
      suggestions: [
        "Make it shorter & punchier",
        "Add a question hook",
        "Generate a strong CTA",
        "Generate 10 hashtags",
      ],
      connectFirstTitle: "Connect a channel first",
      connectFirstBody: "Publishing actions become available after OAuth connection.",
      noChannelSelected: "No channel selected",
      previewEmpty: "Select a connected channel to preview.",
      livePreview: "Live preview",
      destinationCount: (count: number) => `${count} destinations`,
      noDestination: "No selected publishing destination.",
    },
    channels: {
      eyebrow: "INTEGRATIONS HUB",
      title: "Channels",
      subtitle: "Connect Instagram directly, manage Facebook Pages separately, and keep every token visible.",
      connectInstagram: "Connect Instagram",
      connectFacebook: "Connect Facebook Page",
      pages: "Pages",
      loadError: "Unable to load channels",
      signInAgain: "Sign in again before connecting a channel",
      authStartFailed: "Unable to start authorization",
      connectedToast: (name: string) => `${name} connected`,
      tiktokSoon: "TikTok connection is coming soon",
      disconnectConfirm: (name: string) => `Disconnect ${name}?`,
      disconnectedToast: "Channel disconnected",
      disconnectFailed: "Unable to disconnect channel",
      filterAll: "All",
      filterConnected: "Connected",
      filterNeedsAction: "Needs action",
      filterReauth: "Re-auth",
      filterDisconnected: "Disconnected",
      instagramNoticeTitle: "Instagram now opens Instagram Login.",
      instagramNoticeBody: "Facebook Pages stay on Facebook Login because Page permissions belong to Meta Pages.",
      pagesSnapshotTitle: "Facebook Pages",
      pagesSnapshotBody: "Each Page is treated as its own publishing destination.",
      openPages: "Open Pages",
      linkedIg: (name: string) => `Linked IG: ${name}`,
      noLinkedIg: "No linked Instagram Page asset",
      followers: "Followers",
      lastSync: "Last sync",
      token: "Token",
      tokenHealth: "Token health",
      statusConnected: "Connected",
      statusWarning: "Needs action",
      statusError: "Re-auth required",
      statusDisconnected: "Disconnected",
      errorMessages: {
        plan_limit_exceeded: "Your current plan has reached its connected channel limit.",
        instagram_not_linked: "No eligible Instagram Business or Creator account is linked to this Page.",
        instagram_provider_config: "Instagram Login is not configured yet. Add Instagram app credentials and callback URL.",
        instagram_permissions: "Instagram did not grant the permissions required for this connection.",
        instagram_professional_required: "Instagram connection requires a Business or Creator account.",
        instagram_callback: "Instagram authorization could not be completed.",
        meta_permissions: "Meta did not grant the permissions required for publishing.",
        provider_config: "This provider is not configured for this deployment yet.",
      },
      unknownError: (code: string) => `Channel connection failed: ${code}`,
    },
    calendar: {
      title: "Calendar",
      subtitle: "Plan the week. Click a day for details.",
      today: "Today",
      views: { Month: "Month", Week: "Week", List: "List" },
      previous: "Previous period",
      next: "Next period",
      selectedDay: "Selected day",
      nothingScheduled: "Nothing scheduled",
      emptyBody: "Add content to fill this day.",
      noPosts: "No posts",
      more: (count: number) => `+${count} more`,
      headers: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      tablePost: "Post",
      tableChannels: "Channels",
      tableDate: "Date",
      tableTime: "Time",
    },
    queue: {
      title: "Queue",
      subtitle: "Drafts, scheduled and failed posts in one place.",
      tabs: ["All", "Drafts", "Scheduled", "Failed"],
      publishingComplete: "Publishing complete",
      publishFailed: "Unable to publish",
      deleteConfirm: "Delete this post from the queue?",
      deleted: "Post deleted",
      deleteFailed: "Unable to delete",
      tablePost: "Post",
      tableChannels: "Channels",
      tableScheduled: "Scheduled",
      tableStatus: "Status",
      tableActions: "Actions",
      noPosts: "No posts in this view.",
    },
    published: {
      title: "Published",
      subtitle: "Recent posts and their performance.",
      fallbackPost: "Published post",
      noPosts: "No published posts yet.",
    },
    analytics: {
      title: "Analytics",
      subtitle: (days: number) => `Cross-channel performance for the last ${days} days.`,
      lastDays: (days: number) => `Last ${days} days`,
      aiSummary: "AI summary",
      aiTitle: "Your live rollups are ready for review.",
      aiBody: "Use reach, engagement and imported account performance to shape the next publishing window.",
      reachOverTime: "Reach over time",
      syncToFill: "Sync analytics to fill this chart.",
      topPosts: "Top posts",
      noSyncedPosts: "No synced posts yet.",
      platformComparison: "Platform comparison",
    },
    media: {
      title: "Media Library",
      subtitle: "Reusable assets for every post.",
      loadError: "Unable to load media",
      uploaded: "Media uploaded",
      uploadFailed: "Upload failed",
      deleteConfirm: "Delete this media asset?",
      deleted: "Media deleted",
      deleteFailed: "Unable to delete media",
      search: "Search assets...",
      tagsSoon: "Tag filters will appear after media tagging is enabled.",
      tags: "Tags",
      filters: ["All", "Images", "Videos"],
      dropTitle: "Drop files here or click to upload",
      dropBody: "PNG, JPG, MP4 up to 200MB",
      deleteMedia: "Delete media",
      mediaAsset: "media asset",
      empty: "No media assets yet.",
    },
    settings: {
      title: "Settings",
      subtitle: "Workspace preferences, team and integrations.",
      sections: {
        profile: "Workspace",
        team: "Team",
        billing: "Billing",
        integrations: "Integrations",
        api: "API keys",
        notif: "Notifications",
      },
      workspaceName: "Workspace name",
      timezone: "Default timezone",
      brandVoice: "Brand voice",
      brandVoiceValue: "Configure your brand voice for AI-assisted drafts.",
      saved: "Workspace preferences saved locally for this session",
      saveChanges: "Save changes",
      teamTitle: "Team members",
      teamText: "Team membership is managed by workspace RBAC. Invite controls will appear when workspace administration is enabled.",
      integrationsTitle: "Integrations",
      integrationsText: "Social OAuth connections are managed from Channels. Webhook integrations are not enabled yet.",
      apiTitle: "API keys",
      apiText: "Public API access is not enabled. Server credentials remain private.",
      notifications: ["Post published successfully", "Post failed to publish", "Weekly analytics digest", "Team mentions"],
      billingTitle: "Billing",
      billingLoad: "Loading billing...",
      billingLoadError: "Unable to load billing",
      currentPlan: (name: string) => `Current plan: ${name}. Payments are handled by Stripe Checkout.`,
      stripeMissing: "Stripe is not configured yet. Free plan stays active until Stripe keys and price IDs are added.",
      active: "Active",
      included: "Included",
      opening: "Opening...",
      upgrade: "Upgrade",
      priceMissing: "Price missing",
      checkoutUnavailable: "Checkout is not available yet",
      portalUnavailable: "Billing portal is not available yet",
      manageBilling: "Manage billing",
      openingPortal: "Opening portal...",
      refresh: "Refresh",
      used: (value: string) => `Used ${value}`,
      limits: {
        channels: "Channels",
        scheduled: "Scheduled posts",
        ai: "AI requests",
        media: "Media storage",
        team: "Team members",
        analytics: "Analytics history",
      },
    },
    ai: {
      title: "AI Assistant",
      subtitle: "Your on-brand writer, planner and hashtag generator.",
      starters: [
        "Plan 7 posts for my restaurant",
        "Rewrite this caption for Instagram",
        "Generate a launch campaign",
        "Suggest the best posting time",
      ],
      welcome: "What should we create today?",
      failed: "AI request failed",
      empty: "No suggestions returned.",
      thinking: "Creator AI is thinking...",
      placeholder: "Ask anything...",
      send: "Send",
    },
    pages: {
      eyebrow: "PAGE CONTROL",
      title: "Facebook Pages",
      subtitle: "List, verify, and reconnect every Page destination separately.",
      connectFacebook: "Connect Facebook Page",
      connectInstagram: "Connect Instagram",
      signInAgain: "Sign in again before connecting a Page.",
      authStartFailed: "Unable to start authorization.",
      loadError: "Unable to load Pages.",
      connectedPages: "Connected Pages",
      needsReconnect: "Needs Reconnect",
      linkedInstagram: "Linked Instagram",
      emptyTitle: "No Facebook Pages connected",
      emptyBody: "Connect Facebook first to import every Page you manage. Instagram can still connect separately with Instagram Login.",
      pageId: (id: string) => `Page ID: ${id}`,
      pageIdMissing: "Page id unavailable",
      ready: "Ready",
      reconnect: "Reconnect",
      publishPermission: "Publish permission",
      linkedIg: "Linked Instagram",
      needsReconnectValue: "Needs reconnect",
      notLinked: "Not linked",
      reconnectPage: "Reconnect Page",
    },
  },
  ar: {
    common: {
      addPost: "إضافة بوست",
      allPosts: "كل البوستات",
      askAi: "اسأل الذكاء",
      by: "بواسطة",
      channels: "القنوات",
      clicks: "النقرات",
      connect: "ربط",
      connected: "متصل",
      connectChannel: "اربط قناة",
      delete: "حذف",
      disconnect: "فصل الربط",
      edit: "تعديل",
      engagement: "التفاعل",
      failed: "فشل",
      granted: "ممنوحة",
      hideFailed: "إخفاء الفاشلة",
      impressions: "مرات الظهور",
      missing: "ناقصة",
      newPost: "بوست جديد",
      notConnected: "غير متصل",
      opening: "جاري الفتح...",
      publishNow: "انشر الآن",
      reach: "الوصول",
      reconnect: "إعادة الربط",
      save: "حفظ",
      showAll: "عرض الكل",
      synced: "متزامن",
      unknownDate: "تاريخ غير معروف",
      untitledPost: "بوست بدون عنوان",
      upload: "رفع",
      uploading: "جاري الرفع...",
      viewAll: "عرض الكل",
    },
    dashboard: {
      title: "مركز قيادة المحتوى",
      scheduledSummary: (posts: number, channels: number) =>
        `عندك ${posts} بوست مجدول على ${channels} قناة.`,
      statScheduled: "بوستات مجدولة",
      statPublished: "تم نشرها",
      statDrafts: "مسودات",
      statChannels: "قنوات مربوطة",
      hintQueue: "طابور النشر",
      hintPublished: "نتائج مكتملة",
      hintDrafts: "أفكار محفوظة",
      hintChannels: "وجهات نشطة",
      gettingStarted: "ابدأ صح",
      stepsComplete: (done: number, total: number) => `${done} من ${total} خطوات مكتملة`,
      checklist: [
        "اربط أول قناة",
        "اكتب أول بوست",
        "جهز أسبوع محتوى",
        "راجع أول تقرير أداء",
      ],
      aiInsight: "رؤية ذكية",
      queueHealthy: "طابور النشر حالته ممتازة.",
      nextWindowOpen: "نافذة النشر الجاية مفتوحة.",
      aiBody: "خلّي ذكاء المبدع يقترح الخطوة الجاية بناء على حالة مساحة العمل الحقيقية.",
      todaysQueue: "طابور اليوم",
      noScheduled: "لا توجد بوستات مجدولة حتى الآن.",
      topPost: "أفضل بوست",
      performance: "الأداء",
      publishedPlaceholder: "نتائج البوستات المنشورة هتظهر هنا.",
      channelHealth: "حالة القنوات",
      manage: "إدارة",
      publishingReady: "جاهزة للنشر",
      needsAttention: "تحتاج متابعة",
    },
    create: {
      editTitle: "تعديل البوست",
      title: "كتابة بوست",
      subtitle: (autosave: string) => `اكتب مرة واحدة وراجع المعاينة لكل منصة. ${autosave}`,
      saved: "محفوظ",
      saving: "جاري الحفظ...",
      saveDraft: "حفظ كمسودة",
      schedule: "جدولة",
      ready: "جاهز",
      selectedBadge: (count: number) => `${count} قناة`,
      loadError: "تعذر تحميل محرر البوست",
      mediaUploaded: "تم رفع الميديا",
      uploadFailed: "فشل رفع الملف",
      requireContent: "اكتب كابشن أو ارفع ميديا الأول",
      requireDestination: "اربط واختر قناة واحدة على الأقل للنشر",
      requireTime: "اختار وقت الجدولة",
      published: "تم تنفيذ النشر",
      draftSaved: "تم حفظ المسودة",
      scheduled: "تمت جدولة البوست",
      saveFailed: "تعذر حفظ البوست",
      aiRewritePrompt: "أعد كتابة هذا الكابشن ليكون أوضح وأكثر جذبًا وجاهزًا للنشر على المنصة.",
      aiRewriteFailed: "فشلت إعادة الكتابة بالذكاء",
      aiRewriteAdded: "تمت إضافة نسخة محسّنة",
      linkPrompt: "اكتب الرابط الذي تريد إضافته للبوست",
      suggestionPrompt: (suggestion: string) => `${suggestion}. أعد نتيجة واحدة جاهزة للاستخدام فقط.`,
      suggestionFailed: "فشل الاقتراح الذكي",
      suggestionAdded: "تمت إضافة الاقتراح",
      noChannelToPublish: "اربط قناة عشان تقدر تنشر.",
      composerPlaceholder: "اكتب البوست هنا...",
      toolMedia: "ميديا",
      toolHashtags: "هاشتاجات",
      toolLink: "رابط",
      toolEmoji: "إيموجي",
      aiRewrite: "تحسين بالذكاء",
      media: "الميديا",
      aiSuggestions: "اقتراحات ذكية",
      suggestions: [
        "اختصره وخليه أقوى",
        "أضف Hook على شكل سؤال",
        "اكتب دعوة واضحة للتفاعل",
        "اقترح 10 هاشتاجات",
      ],
      connectFirstTitle: "اربط قناة الأول",
      connectFirstBody: "أزرار النشر هتشتغل بعد إتمام ربط الحسابات.",
      noChannelSelected: "لا توجد قناة مختارة",
      previewEmpty: "اختر قناة متصلة عشان تشوف المعاينة.",
      livePreview: "معاينة مباشرة",
      destinationCount: (count: number) => `${count} وجهات`,
      noDestination: "لا توجد وجهة نشر محددة.",
    },
    channels: {
      eyebrow: "مركز الربط",
      title: "القنوات",
      subtitle: "اربط إنستجرام مباشرة، وافصل إدارة صفحات فيسبوك، وخلي حالة كل توكن واضحة.",
      connectInstagram: "ربط إنستجرام",
      connectFacebook: "ربط صفحة فيسبوك",
      pages: "الصفحات",
      loadError: "تعذر تحميل القنوات",
      signInAgain: "سجّل الدخول مرة تانية قبل ربط القناة",
      authStartFailed: "تعذر بدء عملية التفويض",
      connectedToast: (name: string) => `تم ربط ${name}`,
      tiktokSoon: "ربط تيك توك قريبًا",
      disconnectConfirm: (name: string) => `هل تريد فصل ${name}؟`,
      disconnectedToast: "تم فصل القناة",
      disconnectFailed: "تعذر فصل القناة",
      filterAll: "الكل",
      filterConnected: "المتصلة",
      filterNeedsAction: "تحتاج متابعة",
      filterReauth: "إعادة ربط",
      filterDisconnected: "غير المتصلة",
      instagramNoticeTitle: "إنستجرام يفتح الآن من تسجيل دخول إنستجرام.",
      instagramNoticeBody: "صفحات فيسبوك تظل على تسجيل دخول فيسبوك لأن صلاحيات الصفحات تابعة لميتا.",
      pagesSnapshotTitle: "صفحات فيسبوك",
      pagesSnapshotBody: "كل صفحة بتتعامل كوجهة نشر مستقلة.",
      openPages: "فتح الصفحات",
      linkedIg: (name: string) => `إنستجرام مربوط: ${name}`,
      noLinkedIg: "لا يوجد حساب إنستجرام مربوط بهذه الصفحة",
      followers: "المتابعون",
      lastSync: "آخر مزامنة",
      token: "التوكن",
      tokenHealth: "صحة التوكن",
      statusConnected: "متصل",
      statusWarning: "يحتاج متابعة",
      statusError: "إعادة الربط مطلوبة",
      statusDisconnected: "غير متصل",
      errorMessages: {
        plan_limit_exceeded: "الخطة الحالية وصلت للحد الأقصى من القنوات المتصلة.",
        instagram_not_linked: "لا يوجد حساب إنستجرام Business أو Creator مؤهل مربوط بهذه الصفحة.",
        instagram_provider_config: "تسجيل دخول إنستجرام غير مضبوط بعد. أضف بيانات تطبيق إنستجرام ورابط الرجوع.",
        instagram_permissions: "إنستجرام لم يمنح الصلاحيات المطلوبة للربط.",
        instagram_professional_required: "ربط إنستجرام يحتاج حساب Business أو Creator.",
        instagram_callback: "تعذر إكمال تفويض إنستجرام.",
        meta_permissions: "ميتا لم تمنح صلاحيات النشر المطلوبة.",
        provider_config: "مزود الخدمة غير مضبوط لهذا النشر بعد.",
      },
      unknownError: (code: string) => `فشل ربط القناة: ${code}`,
    },
    calendar: {
      title: "التقويم",
      subtitle: "خطط الأسبوع. اضغط على أي يوم عشان تشوف تفاصيله.",
      today: "اليوم",
      views: { Month: "شهر", Week: "أسبوع", List: "قائمة" },
      previous: "الفترة السابقة",
      next: "الفترة التالية",
      selectedDay: "اليوم المحدد",
      nothingScheduled: "لا يوجد محتوى مجدول",
      emptyBody: "أضف محتوى عشان تملا اليوم ده.",
      noPosts: "لا توجد بوستات",
      more: (count: number) => `+${count} أخرى`,
      headers: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
      tablePost: "البوست",
      tableChannels: "القنوات",
      tableDate: "التاريخ",
      tableTime: "الوقت",
    },
    queue: {
      title: "الطابور",
      subtitle: "المسودات والمجدول والفاشل في مكان واحد.",
      tabs: ["الكل", "المسودات", "المجدولة", "الفاشلة"],
      publishingComplete: "تم تنفيذ النشر",
      publishFailed: "تعذر النشر",
      deleteConfirm: "هل تريد حذف البوست من الطابور؟",
      deleted: "تم حذف البوست",
      deleteFailed: "تعذر الحذف",
      tablePost: "البوست",
      tableChannels: "القنوات",
      tableScheduled: "موعد النشر",
      tableStatus: "الحالة",
      tableActions: "الإجراءات",
      noPosts: "لا توجد بوستات في هذا العرض.",
    },
    published: {
      title: "المنشور",
      subtitle: "آخر البوستات المنشورة وأداؤها.",
      fallbackPost: "بوست منشور",
      noPosts: "لا توجد بوستات منشورة حتى الآن.",
    },
    analytics: {
      title: "التحليلات",
      subtitle: (days: number) => `أداء القنوات خلال آخر ${days} يوم.`,
      lastDays: (days: number) => `آخر ${days} يوم`,
      aiSummary: "ملخص ذكي",
      aiTitle: "تجميعات الأداء جاهزة للمراجعة.",
      aiBody: "استخدم الوصول والتفاعل وأداء الحسابات المستوردة لتحديد أفضل نافذة نشر جاية.",
      reachOverTime: "الوصول مع الوقت",
      syncToFill: "زامن التحليلات عشان يظهر الرسم البياني.",
      topPosts: "أفضل البوستات",
      noSyncedPosts: "لا توجد بوستات متزامنة حتى الآن.",
      platformComparison: "مقارنة المنصات",
    },
    media: {
      title: "مكتبة الميديا",
      subtitle: "ملفات قابلة لإعادة الاستخدام في كل بوست.",
      loadError: "تعذر تحميل الميديا",
      uploaded: "تم رفع الميديا",
      uploadFailed: "فشل الرفع",
      deleteConfirm: "هل تريد حذف ملف الميديا ده؟",
      deleted: "تم حذف الميديا",
      deleteFailed: "تعذر حذف الميديا",
      search: "ابحث في الملفات...",
      tagsSoon: "فلاتر الوسوم هتظهر بعد تفعيل وسم الميديا.",
      tags: "الوسوم",
      filters: ["الكل", "صور", "فيديوهات"],
      dropTitle: "اسحب الملفات هنا أو اضغط للرفع",
      dropBody: "PNG و JPG و MP4 حتى 200MB",
      deleteMedia: "حذف الميديا",
      mediaAsset: "ملف ميديا",
      empty: "لا توجد ميديا حتى الآن.",
    },
    settings: {
      title: "الإعدادات",
      subtitle: "تفضيلات مساحة العمل والفريق والتكاملات.",
      sections: {
        profile: "مساحة العمل",
        team: "الفريق",
        billing: "الفوترة",
        integrations: "التكاملات",
        api: "مفاتيح API",
        notif: "الإشعارات",
      },
      workspaceName: "اسم مساحة العمل",
      timezone: "المنطقة الزمنية الافتراضية",
      brandVoice: "صوت البراند",
      brandVoiceValue: "اضبط أسلوب البراند عشان يساعد الذكاء في كتابة مسودات مناسبة.",
      saved: "تم حفظ تفضيلات مساحة العمل لهذه الجلسة",
      saveChanges: "حفظ التغييرات",
      teamTitle: "أعضاء الفريق",
      teamText: "إدارة الفريق مربوطة بصلاحيات مساحة العمل. دعوات الفريق هتظهر بعد تفعيل إدارة المساحات.",
      integrationsTitle: "التكاملات",
      integrationsText: "ربط حسابات السوشيال يتم من صفحة القنوات. تكاملات الويب هوك غير مفعلة حاليًا.",
      apiTitle: "مفاتيح API",
      apiText: "الوصول العام للـ API غير مفعّل. مفاتيح السيرفر تظل خاصة.",
      notifications: ["تم نشر البوست بنجاح", "فشل نشر بوست", "ملخص التحليلات الأسبوعي", "إشارات الفريق"],
      billingTitle: "الفوترة",
      billingLoad: "جاري تحميل الفوترة...",
      billingLoadError: "تعذر تحميل الفوترة",
      currentPlan: (name: string) => `الخطة الحالية: ${name}. الدفع يتم من خلال Stripe Checkout.`,
      stripeMissing: "Stripe غير مضبوط بعد. الخطة المجانية هتفضل مفعلة لحد إضافة المفاتيح وأسعار الخطط.",
      active: "مفعّلة",
      included: "مضمنة",
      opening: "جاري الفتح...",
      upgrade: "ترقية",
      priceMissing: "السعر غير موجود",
      checkoutUnavailable: "الدفع غير متاح حاليًا",
      portalUnavailable: "بوابة الفوترة غير متاحة حاليًا",
      manageBilling: "إدارة الفوترة",
      openingPortal: "جاري فتح البوابة...",
      refresh: "تحديث",
      used: (value: string) => `المستخدم ${value}`,
      limits: {
        channels: "القنوات",
        scheduled: "البوستات المجدولة",
        ai: "طلبات الذكاء",
        media: "تخزين الميديا",
        team: "أعضاء الفريق",
        analytics: "سجل التحليلات",
      },
    },
    ai: {
      title: "مساعد الذكاء",
      subtitle: "كاتب ومخطط ومولد هاشتاجات يحافظ على صوت البراند.",
      starters: [
        "خطط 7 بوستات لمطعم",
        "أعد كتابة الكابشن لإنستجرام",
        "جهز حملة إطلاق",
        "اقترح أفضل وقت للنشر",
      ],
      welcome: "هنشتغل على إيه النهارده؟",
      failed: "فشل طلب الذكاء",
      empty: "لم ترجع اقتراحات.",
      thinking: "ذكاء المبدع بيفكر...",
      placeholder: "اسأل عن أي شيء...",
      send: "إرسال",
    },
    pages: {
      eyebrow: "إدارة الصفحات",
      title: "صفحات فيسبوك",
      subtitle: "اعرض كل صفحة وتأكد من صلاحياتها وأعد ربطها بشكل مستقل.",
      connectFacebook: "ربط صفحة فيسبوك",
      connectInstagram: "ربط إنستجرام",
      signInAgain: "سجّل الدخول مرة تانية قبل ربط صفحة.",
      authStartFailed: "تعذر بدء التفويض.",
      loadError: "تعذر تحميل الصفحات.",
      connectedPages: "الصفحات المتصلة",
      needsReconnect: "تحتاج إعادة ربط",
      linkedInstagram: "إنستجرام مربوط",
      emptyTitle: "لا توجد صفحات فيسبوك متصلة",
      emptyBody: "اربط فيسبوك الأول عشان نستورد كل الصفحات اللي بتديرها. إنستجرام يقدر يتربط بشكل منفصل من تسجيل دخول إنستجرام.",
      pageId: (id: string) => `معرف الصفحة: ${id}`,
      pageIdMissing: "معرف الصفحة غير متاح",
      ready: "جاهزة",
      reconnect: "إعادة ربط",
      publishPermission: "صلاحية النشر",
      linkedIg: "إنستجرام مربوط",
      needsReconnectValue: "تحتاج إعادة ربط",
      notLinked: "غير مربوط",
      reconnectPage: "إعادة ربط الصفحة",
    },
  },
} as const;

export function getPageCopy(locale: Locale) {
  return pageCopy[locale] ?? pageCopy.en;
}

export function formatAppDate(date: Date | string | number, locale: Locale, enPattern: string, arPattern = enPattern) {
  const value = date instanceof Date ? date : new Date(date);
  return format(value, locale === "ar" ? arPattern : enPattern, locale === "ar" ? { locale: arDateLocale } : undefined);
}

export function formatAppNumber(value: number, locale: Locale) {
  return value.toLocaleString(locale === "ar" ? "ar-EG" : "en-US");
}

export function getPlatformName(platform: UiPlatform, locale: Locale) {
  if (locale !== "ar") {
    return {
      instagram: "Instagram",
      facebook: "Facebook",
      linkedin: "LinkedIn",
      tiktok: "TikTok",
    }[platform];
  }

  return {
    instagram: "إنستجرام",
    facebook: "فيسبوك",
    linkedin: "لينكدإن",
    tiktok: "تيك توك",
  }[platform];
}

export function getStatusLabel(status: UiPostStatus, locale: Locale) {
  const labels = {
    en: {
      draft: "Draft",
      scheduled: "Scheduled",
      publishing: "Publishing",
      published: "Published",
      failed: "Failed",
    },
    ar: {
      draft: "مسودة",
      scheduled: "مجدول",
      publishing: "جاري النشر",
      published: "منشور",
      failed: "فشل",
    },
  };

  return labels[locale][status];
}

export function getPermissionLabel(name: string, locale: Locale) {
  if (locale !== "ar") return name;

  const labels: Record<string, string> = {
    "Manage Page posts": "إدارة منشورات الصفحة",
    "Read Page analytics": "قراءة تحليلات الصفحة",
    "Instagram Login": "تسجيل دخول إنستجرام",
    "Linked Page access": "الوصول عبر الصفحة المربوطة",
    "Publish media": "نشر الميديا",
    "Publish posts": "نشر البوستات",
    "Read analytics": "قراءة التحليلات",
  };

  return labels[name] ?? name;
}
